DROP TABLE IF EXISTS EventsParticipants;
DROP TABLE IF EXISTS EventsTags;
DROP TABLE IF EXISTS UsersEvents;
DROP TABLE IF EXISTS Events;
DROP TABLE IF EXISTS Cities;
DROP TABLE IF EXISTS Participants;
DROP TABLE IF EXISTS Tags;
DROP TABLE IF EXISTS Users;